extends Node

signal hide_layers
signal show_layers
signal open_inventory
signal open_inventory_generate_itemslot
signal open_inventory_button(int)
signal open_inventory_hide_border
signal open_inventory_hide_button
signal test
