extends Node

signal pain_reduct
signal pain_increase
signal brain_reduct
signal brain_increase
signal hide_layers
signal show_layers
signal open_inventory
signal block_button_inv
signal block_button_inv_off
signal self_destroy_inv_other_menu
signal get_child_other_inv
